name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Application to EC2
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.EC2_KEY }}

    - name: Copy Files to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          cd ~/app || git clone https://github.com/myself-yash/Mysql-CRUD-Operations-With-Nodejs-And-Reactjs.git ~/app
          cd ~/app
          git pull origin main
          cp ../.env .
        EOF
    - name: Deploy Docker Containers
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          cd ~/app
          docker-compose down
          docker rmi $(docker images)
          docker system prune -f
          docker-compose up --build -d
        EOF
